[2025-04-03T18:12:03.730+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/day.py
[2025-04-03T18:12:03.731+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:12:03.731+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:12:03.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:12:03.741+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:12:03.740+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:12:03.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:12:03.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.027 seconds
[2025-04-03T18:12:34.049+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/day.py
[2025-04-03T18:12:34.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:12:34.050+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:12:34.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:12:34.059+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:12:34.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:12:34.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:12:34.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.043 seconds
[2025-04-03T18:13:04.230+0000] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/day.py
[2025-04-03T18:13:04.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:13:04.236+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:13:04.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:13:04.244+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:13:04.243+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:13:04.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:13:04.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.044 seconds
[2025-04-03T18:13:34.410+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/day.py
[2025-04-03T18:13:34.418+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:13:34.419+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:13:34.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:13:34.429+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:13:34.427+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:13:34.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:13:34.460+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.055 seconds
[2025-04-03T18:14:04.605+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/day.py
[2025-04-03T18:14:04.613+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:14:04.615+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:14:04.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:14:04.623+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:14:04.622+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:14:04.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:14:04.660+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.060 seconds
[2025-04-03T18:14:34.838+0000] {processor.py:153} INFO - Started process (PID=213) to work on /opt/airflow/dags/day.py
[2025-04-03T18:14:34.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:14:34.840+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:14:34.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:14:34.850+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:14:34.848+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:14:34.850+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:14:34.877+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.043 seconds
[2025-04-03T18:15:05.052+0000] {processor.py:153} INFO - Started process (PID=218) to work on /opt/airflow/dags/day.py
[2025-04-03T18:15:05.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:15:05.062+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:15:05.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:15:05.071+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:15:05.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:15:05.072+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:15:05.103+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.056 seconds
[2025-04-03T18:15:35.248+0000] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/day.py
[2025-04-03T18:15:35.257+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:15:35.258+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:15:35.258+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:15:35.267+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:15:35.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:15:35.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:15:35.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.052 seconds
[2025-04-03T18:16:05.471+0000] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/day.py
[2025-04-03T18:16:05.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:16:05.480+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:16:05.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:16:05.488+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:16:05.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:16:05.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:16:05.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.049 seconds
[2025-04-03T18:16:35.672+0000] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/day.py
[2025-04-03T18:16:35.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:16:35.682+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:16:35.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:16:35.690+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:16:35.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:16:35.690+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:16:35.717+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.051 seconds
[2025-04-03T18:18:33.265+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/day.py
[2025-04-03T18:18:33.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:18:33.266+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:18:33.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:18:33.274+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:18:33.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:18:33.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:18:33.291+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.028 seconds
[2025-04-03T18:19:03.601+0000] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/day.py
[2025-04-03T18:19:03.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:19:03.603+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:03.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:19:03.613+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:03.611+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:19:03.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:19:03.644+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.048 seconds
[2025-04-03T18:19:12.673+0000] {processor.py:153} INFO - Started process (PID=214) to work on /opt/airflow/dags/day.py
[2025-04-03T18:19:12.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:19:12.675+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:12.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:19:12.685+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:12.684+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:19:12.685+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:19:12.715+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.047 seconds
[2025-04-03T18:19:42.909+0000] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/day.py
[2025-04-03T18:19:42.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:19:42.919+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:42.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:19:42.927+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:19:42.926+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:19:42.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:19:42.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.053 seconds
[2025-04-03T18:20:13.101+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/day.py
[2025-04-03T18:20:13.110+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:20:13.111+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:20:13.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:20:13.122+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:20:13.120+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:20:13.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:20:13.162+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.067 seconds
[2025-04-03T18:20:43.305+0000] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/day.py
[2025-04-03T18:20:43.314+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:20:43.315+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:20:43.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:20:43.323+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:20:43.322+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:20:43.323+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:20:43.351+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.051 seconds
[2025-04-03T18:21:13.503+0000] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/day.py
[2025-04-03T18:21:13.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:21:13.513+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:21:13.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:21:13.521+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:21:13.520+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:21:13.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:21:13.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.052 seconds
[2025-04-03T18:21:43.692+0000] {processor.py:153} INFO - Started process (PID=253) to work on /opt/airflow/dags/day.py
[2025-04-03T18:21:43.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:21:43.699+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:21:43.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:21:43.709+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:21:43.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:21:43.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:21:43.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.059 seconds
[2025-04-03T18:22:13.899+0000] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/day.py
[2025-04-03T18:22:13.908+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:22:13.909+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:22:13.909+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:22:13.917+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:22:13.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:22:13.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:22:13.944+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.050 seconds
[2025-04-03T18:22:44.085+0000] {processor.py:153} INFO - Started process (PID=263) to work on /opt/airflow/dags/day.py
[2025-04-03T18:22:44.094+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:22:44.095+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:22:44.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:22:44.104+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:22:44.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:22:44.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:22:44.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.055 seconds
[2025-04-03T18:23:14.303+0000] {processor.py:153} INFO - Started process (PID=268) to work on /opt/airflow/dags/day.py
[2025-04-03T18:23:14.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:23:14.313+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:14.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:23:14.323+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:14.321+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:23:14.324+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:23:14.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.057 seconds
[2025-04-03T18:23:23.379+0000] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/day.py
[2025-04-03T18:23:23.388+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:23:23.389+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:23:23.415+0000] {processor.py:753} INFO - DAG(s) dict_keys(['daily_2pm_dag']) retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:23:23.595+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.595+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:daily_2pm_dag
[2025-04-03T18:23:23.610+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.610+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:daily_2pm_dag
[2025-04-03T18:23:23.620+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.620+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:daily_2pm_dag
[2025-04-03T18:23:23.621+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.621+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-04-03T18:23:23.641+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.641+0000] {dag.py:2711} INFO - Creating ORM DAG for daily_2pm_dag
[2025-04-03T18:23:23.664+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:23.663+0000] {dag.py:3441} INFO - Setting next_dagrun for daily_2pm_dag to 2025-04-03T14:00:00+00:00, run_after=2025-04-04T14:00:00+00:00
[2025-04-03T18:23:23.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.325 seconds
[2025-04-03T18:23:49.607+0000] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/day.py
[2025-04-03T18:23:49.616+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:23:49.617+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:49.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:23:49.629+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:23:49.627+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:23:49.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:23:49.663+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.061 seconds
[2025-04-03T18:24:19.786+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/day.py
[2025-04-03T18:24:19.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:24:19.797+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:19.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:24:19.805+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:19.804+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:24:19.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:24:19.842+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.062 seconds
[2025-04-03T18:24:21.865+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/day.py
[2025-04-03T18:24:21.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:24:21.867+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:21.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:24:21.876+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:21.874+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:24:21.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:24:21.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.043 seconds
[2025-04-03T18:24:34.978+0000] {processor.py:153} INFO - Started process (PID=293) to work on /opt/airflow/dags/day.py
[2025-04-03T18:24:34.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:24:34.988+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:34.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:24:34.998+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:34.996+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:24:34.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:24:35.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.053 seconds
[2025-04-03T18:24:48.084+0000] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/day.py
[2025-04-03T18:24:48.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:24:48.094+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:48.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:24:48.105+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:24:48.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:24:48.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:24:48.131+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.052 seconds
[2025-04-03T18:26:30.370+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/day.py
[2025-04-03T18:26:30.370+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:26:30.371+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:26:30.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:26:30.380+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:26:30.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:26:30.380+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:26:30.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.025 seconds
[2025-04-03T18:27:00.688+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/day.py
[2025-04-03T18:27:00.689+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:27:00.690+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:27:00.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:27:00.699+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:27:00.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:27:00.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:27:00.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.043 seconds
[2025-04-03T18:27:30.892+0000] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/day.py
[2025-04-03T18:27:30.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:27:30.902+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:27:30.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:27:30.911+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:27:30.909+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:27:30.911+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:27:30.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.052 seconds
[2025-04-03T18:28:01.105+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/day.py
[2025-04-03T18:28:01.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:28:01.115+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:28:01.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:28:01.124+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:28:01.123+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:28:01.124+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:28:01.156+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.056 seconds
[2025-04-03T18:33:18.116+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/day.py
[2025-04-03T18:33:18.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:33:18.118+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:33:18.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:33:18.127+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:33:18.126+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:33:18.127+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:33:18.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.028 seconds
[2025-04-03T18:34:08.969+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/day.py
[2025-04-03T18:34:08.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:34:08.970+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:34:08.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:34:08.983+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:34:08.982+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:34:08.983+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:34:09.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.034 seconds
[2025-04-03T18:34:39.299+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/day.py
[2025-04-03T18:34:39.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/day.py for tasks to queue
[2025-04-03T18:34:39.301+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:34:39.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/day.py
[2025-04-03T18:34:39.311+0000] {logging_mixin.py:137} INFO - [2025-04-03T18:34:39.310+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/day.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/day.py", line 4, in <module>
    from scripts.task_functions import task_1, task_2  # Import the functions from the script
ModuleNotFoundError: No module named 'scripts'
[2025-04-03T18:34:39.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/day.py
[2025-04-03T18:34:39.344+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/day.py took 0.050 seconds
