[2025-07-31T12:27:44.359+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-31T12:27:44.370+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.check_table_task manual__2025-07-31T12:27:32.067267+00:00 [queued]>
[2025-07-31T12:27:44.374+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.check_table_task manual__2025-07-31T12:27:32.067267+00:00 [queued]>
[2025-07-31T12:27:44.375+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-07-31T12:27:44.382+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_table_task> on 2025-07-31 12:27:32.067267+00:00
[2025-07-31T12:27:44.391+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=761) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T12:27:44.392+0000] {standard_task_runner.py:72} INFO - Started process 763 to run task
[2025-07-31T12:27:44.391+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'world_population_ETL_dag_43', 'check_table_task', 'manual__2025-07-31T12:27:32.067267+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/project_01_dag.py', '--cfg-path', '/tmp/tmp115zctuh']
[2025-07-31T12:27:44.393+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask check_table_task
[2025-07-31T12:27:44.424+0000] {task_command.py:467} INFO - Running <TaskInstance: world_population_ETL_dag_43.check_table_task manual__2025-07-31T12:27:32.067267+00:00 [running]> on host 1e069286f646
[2025-07-31T12:27:44.479+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='givi-abe' AIRFLOW_CTX_DAG_ID='world_population_ETL_dag_43' AIRFLOW_CTX_TASK_ID='check_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T12:27:32.067267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T12:27:32.067267+00:00'
[2025-07-31T12:27:44.480+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-31T12:27:44.497+0000] {logging_mixin.py:190} INFO - Primary key column already exists in table.
[2025-07-31T12:27:44.498+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-31T12:27:44.505+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-31T12:27:44.506+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=world_population_ETL_dag_43, task_id=check_table_task, run_id=manual__2025-07-31T12:27:32.067267+00:00, execution_date=20250731T122732, start_date=20250731T122744, end_date=20250731T122744
[2025-07-31T12:27:44.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-31T12:27:44.543+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-31T12:27:44.544+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
