[2025-07-31T13:43:12.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-31T13:43:12.720+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T13:41:00.804261+00:00 [queued]>
[2025-07-31T13:43:12.729+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T13:41:00.804261+00:00 [queued]>
[2025-07-31T13:43:12.730+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-07-31T13:43:12.751+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_and_insert_task> on 2025-07-31 13:41:00.804261+00:00
[2025-07-31T13:43:12.771+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1010) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T13:43:12.773+0000] {standard_task_runner.py:72} INFO - Started process 1012 to run task
[2025-07-31T13:43:12.772+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'world_population_ETL_dag_43', 'consume_and_insert_task', 'manual__2025-07-31T13:41:00.804261+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/project_01_dag.py', '--cfg-path', '/tmp/tmp767_2pr4']
[2025-07-31T13:43:12.775+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask consume_and_insert_task
[2025-07-31T13:43:12.835+0000] {task_command.py:467} INFO - Running <TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T13:41:00.804261+00:00 [running]> on host 5caea9b1d396
[2025-07-31T13:43:12.940+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='givi-abe' AIRFLOW_CTX_DAG_ID='world_population_ETL_dag_43' AIRFLOW_CTX_TASK_ID='consume_and_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T13:41:00.804261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T13:41:00.804261+00:00'
[2025-07-31T13:43:12.941+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-31T13:43:12.960+0000] {conn.py:396} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T13:43:12.964+0000] {conn.py:618} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-31T13:43:12.964+0000] {conn.py:457} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T13:43:12.966+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('ETL-PROJECT',)
[2025-07-31T13:43:12.966+0000] {logging_mixin.py:190} INFO - üì° Kafka consumer started. Waiting for partition assignment...
[2025-07-31T13:43:12.969+0000] {conn.py:396} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T13:43:12.969+0000] {conn.py:457} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T13:43:12.969+0000] {conn.py:945} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T13:43:13.072+0000] {cluster.py:401} INFO - Coordinator for group/etl-consumer-group is ('coordinator-1', 'kafka', 9092, None)
[2025-07-31T13:43:13.073+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl-consumer-group
[2025-07-31T13:43:13.073+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-31T13:43:13.074+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl-consumer-group
[2025-07-31T13:43:13.075+0000] {base.py:419} INFO - Failed to join group etl-consumer-group: NodeNotReadyError: coordinator-1
[2025-07-31T13:43:13.076+0000] {conn.py:396} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T13:43:13.077+0000] {conn.py:457} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T13:43:13.178+0000] {base.py:532} INFO - (Re-)joining group etl-consumer-group
[2025-07-31T13:43:13.181+0000] {base.py:637} INFO - Received member id etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7-ba5b01ba-fae6-4ed8-8a34-b97c60c96960 for group etl-consumer-group; will retry join-group
[2025-07-31T13:43:13.181+0000] {base.py:419} INFO - Failed to join group etl-consumer-group: [Error 79] MemberIdRequiredError
[2025-07-31T13:43:13.182+0000] {base.py:532} INFO - (Re-)joining group etl-consumer-group
[2025-07-31T13:43:17.043+0000] {base.py:594} INFO - Successfully joined group etl-consumer-group <Generation 8 (member_id: etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7-ba5b01ba-fae6-4ed8-8a34-b97c60c96960, protocol: range)>
[2025-07-31T13:43:17.046+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-07-31T13:43:17.047+0000] {consumer.py:249} INFO - Setting newly assigned partitions () for group etl-consumer-group
[2025-07-31T13:43:22.971+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è No partitions assigned after 10 seconds
[2025-07-31T13:43:22.972+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-31T13:43:22.972+0000] {base.py:891} INFO - Leaving consumer group (etl-consumer-group).
[2025-07-31T13:43:22.975+0000] {base.py:906} INFO - LeaveGroup request for group etl-consumer-group returned successfully
[2025-07-31T13:43:22.975+0000] {conn.py:945} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T13:43:22.976+0000] {conn.py:945} INFO - <BrokerConnection client_id=etl-consumer-client-a826a906-23ad-4cb1-88bb-cc9daf5e2bc7, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T13:43:22.977+0000] {logging_mixin.py:190} INFO - üîå Resources cleaned up
[2025-07-31T13:43:22.977+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-31T13:43:22.993+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-31T13:43:22.994+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=world_population_ETL_dag_43, task_id=consume_and_insert_task, run_id=manual__2025-07-31T13:41:00.804261+00:00, execution_date=20250731T134100, start_date=20250731T134312, end_date=20250731T134322
[2025-07-31T13:43:23.036+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-31T13:43:23.071+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-31T13:43:23.074+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
